---
title: "Final Project HUDM 6026"
author: "Getong Zhong & Frank Li"
date: "2023-05-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
setwd("C:/Users/tonyg/Desktop/Academic/Grad/HUDM 6026")
# Import data set
data <- read.csv("Walmart_Store_sales.csv", header = TRUE) 
# Run a simple linear regression model 
model <- lm (Weekly_Sales ~ Temperature, data = data)
summary(model)
```
## 2. Data generation
We take only "Temperature" as the predict variable and “Weekly_Sales” as the response variable.
```{r}
dat_gen <- function(n, beta_0, beta_1, beta_2, beta_3, beta_4, x_dist, sigma) {
  x1 <- x_dist(n)
  y <- beta_0 + beta_1 * x1 + rnorm(n, mean = 0, sd = sigma)
  return(data.frame(Temperature = x1, Weekly_sales = y))
}

data_simulation <- dat_gen(n = nrow(data), beta_0 = model$coefficients[1], beta_1 = model$coefficients[2], x_dist = rnorm, sigma = summary(model)$sigma)
data_simulation
```

## 3. Estimators 
```{r}
reg <- function(data) {
  n <- nrow(data)
  xbar <- mean(data[,1])
  ybar <- mean(data[,2])
  # estimate beta1 using the least squares estimator
  beta1 <- sum((data$Temperature - xbar) * (data$Weekly_sales - ybar)) / sum((data$Temperature - xbar)^2)
  
  # estimate beta1 using the alternative estimator
  beta1a <- 1 / mean((data$Weekly_sales - ybar) / (data$Temperature - xbar))
  
  # estimate sigma^2 using the usual estimator
  sig2 <- sum((data$Weekly_sales - predict(lm(Weekly_sales ~ Temperature, data = data))^2) / (n - 2))
  
  # estimate sigma^2 using the alternative estimator
  sig2a <- sum((data$Weekly_sales - predict(lm(Weekly_sales ~ Temperature, data = data)))^2) / n
  
  return(list(beta1a = beta1,
              beta1_a = beta1a,
              sigama2 = sig2,
              sigama2a = sig2a))
}
```

### New data
```{r}
reg_results <- reg(data_simulation)
reg_results
mean(data[,1])
```